from app.models import Player

# Player data separated for reuse; stats are illustrative sample values.
PLAYERS: list[Player] = [
    Player(player_id=1, name="Lionel Messi", goals=30, passes=1800, assists=18, shots=120, position="Forward", age=36, leagues=["MLS"], matches_own=34),
    Player(player_id=2, name="Cristiano Ronaldo", goals=24, passes=900, assists=6, shots=110, position="Forward", age=38, leagues=["Saudi Pro League"], matches_own=30),
    Player(player_id=3, name="Kylian Mbappé", goals=28, passes=950, assists=10, shots=115, position="Forward", age=25, leagues=["Ligue 1"], matches_own=32),
    Player(player_id=4, name="Neymar Jr.", goals=12, passes=720, assists=9, shots=70, position="Forward", age=31, leagues=["Ligue 1"], matches_own=20),
    Player(player_id=5, name="Kevin De Bruyne", goals=10, passes=2000, assists=16, shots=70, position="Midfielder", age=32, leagues=["Premier League"], matches_own=33),
    Player(player_id=6, name="Mohamed Salah", goals=26, passes=850, assists=9, shots=120, position="Forward", age=30, leagues=["Premier League"], matches_own=34),
    Player(player_id=7, name="Robert Lewandowski", goals=35, passes=600, assists=7, shots=140, position="Forward", age=35, leagues=["La Liga"], matches_own=36),
    Player(player_id=8, name="Erling Haaland", goals=36, passes=400, assists=8, shots=130, position="Forward", age=23, leagues=["Premier League"], matches_own=34),
    Player(player_id=9, name="Harry Kane", goals=20, passes=700, assists=11, shots=110, position="Forward", age=30, leagues=["Premier League"], matches_own=32),
    Player(player_id=10, name="Karim Benzema", goals=18, passes=650, assists=12, shots=85, position="Forward", age=35, leagues=["La Liga"], matches_own=28),
    Player(player_id=11, name="Luka Modrić", goals=4, passes=1600, assists=8, shots=40, position="Midfielder", age=38, leagues=["La Liga"], matches_own=30),
    Player(player_id=12, name="N'Golo Kanté", goals=2, passes=900, assists=4, shots=25, position="Midfielder", age=32, leagues=["Premier League"], matches_own=26),
    Player(player_id=13, name="Bruno Fernandes", goals=14, passes=1100, assists=10, shots=70, position="Midfielder", age=29, leagues=["Premier League"], matches_own=34),
    Player(player_id=14, name="Sadio Mané", goals=15, passes=520, assists=6, shots=80, position="Forward", age=31, leagues=["Premier League"], matches_own=29),
    Player(player_id=15, name="Raheem Sterling", goals=11, passes=780, assists=7, shots=65, position="Forward", age=28, leagues=["Premier League"], matches_own=30),
    Player(player_id=16, name="Virgil van Dijk", goals=5, passes=700, assists=2, shots=30, position="Defender", age=32, leagues=["Premier League"], matches_own=33),
    Player(player_id=17, name="Sergio Ramos", goals=6, passes=450, assists=1, shots=30, position="Defender", age=36, leagues=["La Liga"], matches_own=20),
    Player(player_id=18, name="Sergio Busquets", goals=1, passes=1400, assists=6, shots=10, position="Midfielder", age=34, leagues=["La Liga"], matches_own=25),
    Player(player_id=19, name="Antoine Griezmann", goals=13, passes=800, assists=9, shots=75, position="Forward", age=31, leagues=["La Liga"], matches_own=30),
    Player(player_id=20, name="Paulo Dybala", goals=8, passes=600, assists=7, shots=50, position="Forward", age=29, leagues=["Serie A"], matches_own=22),
    Player(player_id=21, name="Manuel Neuer", goals=0, passes=300, assists=1, shots=5, position="Goalkeeper", age=37, leagues=["Bundesliga"], matches_own=28),
    Player(player_id=22, name="Jan Oblak", goals=0, passes=150, assists=0, shots=5, position="Goalkeeper", age=29, leagues=["La Liga"], matches_own=30),
    Player(player_id=23, name="Alisson Becker", goals=0, passes=400, assists=1, shots=7, position="Goalkeeper", age=31, leagues=["Premier League"], matches_own=34),
    Player(player_id=24, name="Thibaut Courtois", goals=0, passes=200, assists=0, shots=3, position="Goalkeeper", age=31, leagues=["La Liga"], matches_own=32),
    Player(player_id=25, name="Jordi Alba", goals=2, passes=900, assists=8, shots=20, position="Defender", age=33, leagues=["La Liga"], matches_own=30),
    Player(player_id=26, name="Trent Alexander-Arnold", goals=6, passes=1200, assists=14, shots=40, position="Defender", age=25, leagues=["Premier League"], matches_own=34),
    Player(player_id=27, name="Phil Foden", goals=18, passes=900, assists=10, shots=85, position="Midfielder", age=23, leagues=["Premier League"], matches_own=33),
    Player(player_id=28, name="Mason Mount", goals=7, passes=650, assists=6, shots=45, position="Midfielder", age=25, leagues=["Premier League"], matches_own=28),
    Player(player_id=29, name="Jadon Sancho", goals=9, passes=520, assists=8, shots=60, position="Forward", age=24, leagues=["Bundesliga"], matches_own=26),
    Player(player_id=30, name="Bernardo Silva", goals=10, passes=1100, assists=9, shots=55, position="Midfielder", age=29, leagues=["Premier League"], matches_own=32),
    Player(player_id=31, name="Rúben Dias", goals=3, passes=750, assists=2, shots=25, position="Defender", age=26, leagues=["Premier League"], matches_own=34),
    Player(player_id=32, name="Koke", goals=4, passes=1000, assists=7, shots=30, position="Midfielder", age=31, leagues=["La Liga"], matches_own=30),
]
