# Player data separated for reuse; stats reflect illustrative current season estimates.
PLAYERS: list[dict] = [
    {"id": 1, "name": "Lionel Messi", "goals": 12, "passes": 1450, "assists": 80, "shots": 72, "position": "Forward", "age": 37, "leagues": ["MLS"], "matches_own": 28, "saves": 0, "clean_sheets": 0},
    {"id": 2, "name": "Cristiano Ronaldo", "goals": 32, "passes": 680, "assists": 40, "shots": 95, "position": "Forward", "age": 39, "leagues": ["Saudi Pro League"], "matches_own": 25, "saves": 0, "clean_sheets": 0},
    {"id": 3, "name": "Kylian Mbappé", "goals": 28, "passes": 820, "assists": 11, "shots": 128, "position": "Forward", "age": 26, "leagues": ["Ligue 1"], "matches_own": 35, "saves": 0, "clean_sheets": 0},
    {"id": 4, "name": "Neymar Jr.", "goals": 8, "passes": 650, "assists": 7, "shots": 55, "position": "Forward", "age": 32, "leagues": ["Ligue 1"], "matches_own": 18, "saves": 0, "clean_sheets": 0},
    {"id": 5, "name": "Kevin De Bruyne", "goals": 14, "passes": 2150, "assists": 19, "shots": 85, "position": "Midfielder", "age": 33, "leagues": ["Premier League"], "matches_own": 35, "saves": 0, "clean_sheets": 0},
    {"id": 6, "name": "Mohamed Salah", "goals": 29, "passes": 920, "assists": 12, "shots": 135, "position": "Forward", "age": 31, "leagues": ["Premier League"], "matches_own": 36, "saves": 0, "clean_sheets": 0},
    {"id": 7, "name": "Robert Lewandowski", "goals": 28, "passes": 720, "assists": 10, "shots": 125, "position": "Forward", "age": 36, "leagues": ["La Liga"], "matches_own": 32, "saves": 0, "clean_sheets": 0},
    {"id": 8, "name": "Erling Haaland", "goals": 41, "passes": 480, "assists": 12, "shots": 148, "position": "Forward", "age": 24, "leagues": ["Premier League"], "matches_own": 37, "saves": 0, "clean_sheets": 0},
    {"id": 9, "name": "Harry Kane", "goals": 24, "passes": 850, "assists": 14, "shots": 125, "position": "Forward", "age": 31, "leagues": ["Premier League"], "matches_own": 35, "saves": 0, "clean_sheets": 0},
    {"id": 10, "name": "Karim Benzema", "goals": 15, "passes": 620, "assists": 10, "shots": 78, "position": "Forward", "age": 36, "leagues": ["La Liga"], "matches_own": 26, "saves": 0, "clean_sheets": 0},
    {"id": 11, "name": "Luka Modrić", "goals": 3, "passes": 1850, "assists": 6, "shots": 35, "position": "Midfielder", "age": 39, "leagues": ["La Liga"], "matches_own": 28, "saves": 0, "clean_sheets": 0},
    {"id": 12, "name": "N'Golo Kanté", "goals": 1, "passes": 1050, "assists": 2, "shots": 18, "position": "Midfielder", "age": 33, "leagues": ["Premier League"], "matches_own": 22, "saves": 0, "clean_sheets": 0},
    {"id": 13, "name": "Bruno Fernandes", "goals": 18, "passes": 1280, "assists": 14, "shots": 65, "position": "Forward", "age": 32, "leagues": ["Premier League"], "matches_own": 24, "saves": 0, "clean_sheets": 0},
    {"id": 15, "name": "Raheem Sterling", "goals": 14, "passes": 820, "assists": 9, "shots": 72, "position": "Forward", "age": 29, "leagues": ["Premier League"], "matches_own": 31, "saves": 0, "clean_sheets": 0},
    {"id": 16, "name": "Virgil van Dijk", "goals": 4, "passes": 820, "assists": 1, "shots": 22, "position": "Defender", "age": 33, "leagues": ["Premier League"], "matches_own": 34, "saves": 0, "clean_sheets": 0},
    {"id": 17, "name": "Sergio Ramos", "goals": 3, "passes": 580, "assists": 0, "shots": 18, "position": "Defender", "age": 37, "leagues": ["La Liga"], "matches_own": 18, "saves": 0, "clean_sheets": 0},
    {"id": 18, "name": "Sergio Busquets", "goals": 0, "passes": 1620, "assists": 4, "shots": 8, "position": "Midfielder", "age": 35, "leagues": ["La Liga"], "matches_own": 24, "saves": 0, "clean_sheets": 0},
    {"id": 19, "name": "Antoine Griezmann", "goals": 11, "passes": 920, "assists": 8, "shots": 68, "position": "Forward", "age": 32, "leagues": ["La Liga"], "matches_own": 28, "saves": 0, "clean_sheets": 0},
    {"id": 20, "name": "Paulo Dybala", "goals": 9, "passes": 680, "assists": 6, "shots": 58, "position": "Forward", "age": 30, "leagues": ["Serie A"], "matches_own": 20, "saves": 0, "clean_sheets": 0},
    {"id": 21, "name": "Manuel Neuer", "position": "Goalkeeper", "age": 38, "leagues": ["Bundesliga"], "matches_own": 26, "passes": 420, "goals": 0, "assists": 0, "shots": 2, "saves": 158, "clean_sheets": 14},
    {"id": 22, "name": "Jan Oblak", "position": "Goalkeeper", "age": 30, "leagues": ["La Liga"], "matches_own": 32, "passes": 280, "goals": 0, "assists": 0, "shots": 3, "saves": 165, "clean_sheets": 17},
    {"id": 23, "name": "Alisson Becker", "position": "Goalkeeper", "age": 32, "leagues": ["Premier League"], "matches_own": 35, "passes": 520, "goals": 0, "assists": 0, "shots": 4, "saves": 162, "clean_sheets": 16},
    {"id": 24, "name": "Thibaut Courtois", "position": "Goalkeeper", "age": 32, "leagues": ["La Liga"], "matches_own": 33, "passes": 360, "goals": 0, "assists": 0, "shots": 2, "saves": 155, "clean_sheets": 15},
    {"id": 27, "name": "Phil Foden", "goals": 22, "passes": 1050, "assists": 14, "shots": 105, "position": "Midfielder", "age": 24, "leagues": ["Premier League"], "matches_own": 35, "saves": 0, "clean_sheets": 0},
    {"id": 28, "name": "Mason Mount", "goals": 10, "passes": 780, "assists": 8, "shots": 58, "position": "Midfielder", "age": 26, "leagues": ["Premier League"], "matches_own": 30, "saves": 0, "clean_sheets": 0},
    {"id": 29, "name": "Jadon Sancho", "goals": 12, "passes": 620, "assists": 10, "shots": 72, "position": "Forward", "age": 25, "leagues": ["Bundesliga"], "matches_own": 29, "saves": 0, "clean_sheets": 0},
    {"id": 30, "name": "Bernardo Silva", "goals": 13, "passes": 1250, "assists": 11, "shots": 72, "position": "Midfielder", "age": 30, "leagues": ["Premier League"], "matches_own": 34, "saves": 0, "clean_sheets": 0},
    {"id": 31, "name": "Rúben Dias", "goals": 2, "passes": 880, "assists": 1, "shots": 16, "position": "Defender", "age": 27, "leagues": ["Premier League"], "matches_own": 35, "saves": 0, "clean_sheets": 0},
    {"id": 32, "name": "Koke", "goals": 5, "passes": 1180, "assists": 8, "shots": 38, "position": "Midfielder", "age": 32, "leagues": ["La Liga"], "matches_own": 32, "saves": 0, "clean_sheets": 0},
]
